name: runner node-app
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
      - run: npm install

      - name: Build
      - run: npm build

      - name: Test
      - run: npm test