name: Two jobs running manually from Github

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Test manual run'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test tags'
        required: false
        type: boolean
  push:
  pull_request:
    types: [ opened ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}